[tool.black]
line-length = 500
target-version = ["py311"]
skip-string-normalization = true

[tool.docformatter]
wrap-summaries = 500
wrap-descriptions = 500
pre-summary-newline = true
make-summary-multi-line = true
force-wrap = true
